# Generated by Django 5.2.1 on 2025-05-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='name',
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='count_item',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во пунктов'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.mainmenu'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='title',
            field=models.CharField(default='Название отсутствует', max_length=50, verbose_name='Пункт меню'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
