# Generated by Django 5.2.1 on 2025-05-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_mainmenu_options_remove_mainmenu_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='count_item',
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='route_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
